token = eth.contract([{constant:false,
    inputs:[{
    name:'receiver',type:'address'},{
    name:'amount',type:'uint256'}],
    name:'sendCoin',
    outputs:[{
        name:'sufficient',type:'bool'}],type:'function'},{constant:true,
    inputs:[{
    name:'',type:'address'}],
    name:'coinBalanceOf',
    outputs:[{
        name:'',type:'uint256'}],type:'function'},{
    inputs:[{
    name:'supply',type:'uint256'}],type:'constructor'},{anonymous:false,
    inputs:[{indexed:false,
    name:'sender',type:'address'},{indexed:false,
    name:'receiver',type:'address'},{indexed:false,
    name:'amount',type:'uint256'}],
    name:'CoinTransfer',type:'event'}]).at('0x1432737ecd736fd780e562e5a768297642673f47')